import "oaidl.idl";
import "ocidl.idl";
import "Wincodec.idl";
import "Wincodecsdk.idl";

[
	uuid(626928FB-282D-41a1-8C7F-57B0AD42EE39),
	version(1.0),
	helpstring("UCI Imaging Format 1.0 Type Library")
]

library UCIImagingLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(4A99BBF1-BB87-437b-BD80-9FC5B7DD0C48),
		helpstring("UCIContainterDecoder Class")
	]

	coclass UCIContainterDecoder
	{
		[default] interface IWICBitmapDecoder;
	};

	[
		uuid(63AF4578-29C3-4bcd-84E3-B63B57F5F264),
		helpstring("UCIFrameDecoder Class")
	]

	coclass UCIFrameDecoder
	{
		[default] interface IWICBitmapFrameDecode;
		interface IWICMetadataBlockReader;
	};
};